language: cpp
sudo: false
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libpq-dev
    - zlib1g-dev
script:
  - cmake -G "Unix Makefiles"
  - make -j4
  - ./bin/sqlite_test
branches:
  only: master
notifications:
  email: false
  irc: false
os: linux